
* Description

Anamnesis is a clipboard manager. It stores all clipboard history and offers
an easy interface to do a full-text search on the items of its history.


* Installing

The recommended installation have three steps:
  1. copy the command-line to the system path
  2. install the anamnesis daemon in the session start-up
  3. create a keyboard shortcut to the graphic interface

There is no automatic tool to do this yet.

1. To install anamnesis command line, create a symbolic link named 'anamnesis' in the
   system path, pointing to anamnesis.py, for example:
      > sudo ln -s /path/to/anamnesis.py /usr/bin/anamnesis

2. Configure the following command to be executed on session start-up (System -> Preferences -> Session Apps):
      > anamnesis --start

3. Configure a shortcut to the graphic interface (System -> Preferences -> Keyboard Shortcuts):
      > anamnesis --browse


* Configuration

Anamnesis will search for configuration files in the $XDG_DATA_DIRS and
$XDG_CONFIG_HOME directories, which defaults to:

#+BEGIN_example
   /usr/share/anamnesis/anamnesis.cfg
   ~/.config/anamnesis/anamnesis.cfg
#+END_example


* Command line

  : Usage: anamnesis [options]
  : 
  : Options:
  :   --version            show program's version number and exit
  :   -h, --help           show this help message and exit
  :   --start              starts anamnesis daemon
  :   --stop               stops anamnesis daemon
  :   --restart            restarts anamnesis daemon
  :   -b, --browser        opens anamnesis browser with clipboard history
  :   --cleanup            optimize database and limit the number of elements
  :   -l N, --list=N       prints the clipboard history last N values
  :   --filter=KEYWORDS    use keywords to filter the clips to be listed
  :   -a CLIP, --add=CLIP  adds a value to the clipboard
  :   --remove=ID          removes the clipboard element with the given id
  :   --brief              print only a brief version of long clipboard elements

Examples:

  Starts the graphic user interface:
#+BEGIN_SRC shell
      anamnesis --browser
#+END_SRC

  Starts the anamnesis daemon:
#+BEGIN_SRC shell
anamnesis --start
#+END_SRC

  Stops the anamnesis daemon:
#+BEGIN_SRC shell
      anamnesis --stop
#+END_SRC

  List the last 20 clipboard items:
#+BEGIN_SRC shell
anamnesis --list=20
#+END_SRC

  List the last 5 items in the clipboard the has the keywords 'my' and 'search':
#+BEGIN_SRC shell
anamnesis --list=5 --filter="my search"
#+END_SRC

  Adds a clipboard item (same as copying to the clipboard if the daemon is running):
#+BEGIN_SRC shell
anamnesis --add="hello, clipboard!"
#+END_SRC


* Dependencies

  - python3
  - sqlite3


* Configuration
  Anamnesis will search for configuration files in the $XDG_DATA_DIRS and $XDG_CONFIG_HOME directories.
  It defaults to:

    /usr/share/anamnesis/anamnesis.cfg
    ~/.config/anamnesis/anamnesis.cfg


* Authors

Written by Fabio Guerra <fabiowguerra@users.sourceforge.net>

Ported to Python 3 by Brian Oney

* TODO Issues
- Enable text search
  - [[file:source/browser.py::clips%20=%20clip_database.search(max_clips,%20keywords)]] 
- Make window pretty again
  - [[file:source/browser.py::#%20def%20apply_treeview_configuration(treeview):]] 
- automate installation

